export enum UserPermission {
  AllPermissions,
  ShowGroup = "ShowGroup",
  AddGroup = "AddGroup",
  EditGroup = "EditGroup",
  DeleteGroup = "DeleteGroup",
  ShowUser = "ShowUser",
  AddUser = "AddUser",
  EditUser = "EditUser",
  DeleteUser = "DeleteUser",
  ShowOrderType = "ShowOrderType",
  AddOrderType = "AddOrderType",
  EditOrderType = "EditOrderType",
  DeleteOrderType = "DeleteOrderType",
  ShowCountry = "ShowCountry",
  AddCountry = "AddCountry",
  EditCountry = "EditCountry",
  DeleteCountry = "DeleteCountry",
  AddRegion = "AddRegion",
  EditRegion = "EditRegion",
  ShowRegion = "ShowRegion",
  DeleteRegion = "DeleteRegion",
  AddClient = "AddClient",
  ShowClient = "ShowClient",
  UpdateClient = "UpdateClient",
  DeleteClient = "DeleteClient",
  ShowCurrency = "ShowCurrency",
  AddCurrency = "AddCurrency",
  UpdateCurrency = "UpdateCurrency",
  DeleteCurrency = "DeleteCurrency",
  ShowDepartment = "ShowDepartment",
  AddDepartment = "AddDepartment",
  UpdateDepartment = "UpdateDepartment",
  ShowIncomeType = "ShowIncomeType",
  AddIncomeType = "AddIncomeType",
  UpdateIncomeType = "UpdateIncomeType",
  DeleteIncomeType = "DeleteIncomeType",
  ShowOutComeType = "ShowOutComeType",
  AddOutComeType = "AddOutComeType",
  UpdateOutComeType = "UpdateOutComeType",




}
